services:
  evoapi:  # Tu servicio evoapi (sin cambios significativos en la lógica, solo labels de Traefik)
    image: atendai/evolution-api:v2.2.3
    restart: always
    container_name: evoapi-dev
    env_file: .env
    environment:
      # Core Configuration
      DOMAIN_NAME: ${DOMAIN_NAME:-localhost}
      SERVER_TYPE: ${SERVER_TYPE:-http}
      SERVER_PORT: ${SERVER_PORT:-8080}
      SERVER_URL: ${SERVER_URL:-https://evoapi.tu-subdominio.com}
      GENERIC_TIMEZONE: ${GENERIC_TIMEZONE:-UTC}
      PORT: ${PORT:-8080}
      
      # Authentication
      AUTHENTICATION_API_KEY: ${AUTHENTICATION_API_KEY:-BAmH4TiAPwBQAy8y2tx41BJXcrBa7y2t}
      AUTHENTICATION_EXPOSE_IN_FETCH_INSTANCES: ${AUTHENTICATION_EXPOSE_IN_FETCH_INSTANCES:-true}
      
      # Cache Configuration
      CACHE_REDIS_URI: ${CACHE_REDIS_URI:-redis://redis:6379/6}
      CACHE_REDIS_ENABLED: ${CACHE_REDIS_ENABLED:-true}
      CACHE_REDIS_PREFIX_KEY: ${CACHE_REDIS_PREFIX_KEY:-evolution_api}
      CACHE_REDIS_SAVE_INSTANCES: ${CACHE_REDIS_SAVE_INSTANCES:-false}
      CACHE_LOCAL_ENABLED: ${CACHE_LOCAL_ENABLED:-false}
      
      # Instance Configuration
      DEL_INSTANCE: ${DEL_INSTANCE:-false}
      
      # CORS Settings
      CORS_ORIGIN: ${CORS_ORIGIN:-*}
      CORS_METHODS: ${CORS_METHODS:-POST,GET,PUT,DELETE}
      CORS_CREDENTIALS: ${CORS_CREDENTIALS:-true}
      
      # Logging
      LOG_LEVEL: ${LOG_LEVEL:-ERROR,WARN}
      LOG_COLOR: ${LOG_COLOR:-true}
      LOG_BAILEYS: ${LOG_BAILEYS:-error}
      
      # Session Configuration
      CONFIG_SESSION_PHONE_CLIENT: ${CONFIG_SESSION_PHONE_CLIENT:-Evolution API V2}
      CONFIG_SESSION_PHONE_NAME: ${CONFIG_SESSION_PHONE_NAME:-Chrome}
      CONFIG_SESSION_PHONE_VERSION: ${CONFIG_SESSION_PHONE_VERSION:-2.3000.1015901307}
      
      # QR Code Settings
      QRCODE_LIMIT: ${QRCODE_LIMIT:-1902}
      QRCODE_COLOR: ${QRCODE_COLOR:-#000000}
      
      # Provider Configuration
      PROVIDER_ENABLED: ${PROVIDER_ENABLED:-false}
      PROVIDER_HOST: ${PROVIDER_HOST:-127.0.0.1}
      PROVIDER_PORT: ${PROVIDER_PORT:-5656}
      PROVIDER_PREFIX: ${PROVIDER_PREFIX:-evolution_api}
      
      # Database Configuration
      DATABASE_ENABLED: ${DATABASE_ENABLED:-true}
      DATABASE_PROVIDER: ${DATABASE_PROVIDER:-postgresql}
      DATABASE_CONNECTION_URI: ${DATABASE_CONNECTION_URI:-postgresql://postgres:BAmH4TiAPwBQAy8y2tx41BJXcrBa7y2t@postgres:5432/evolution2}
      DATABASE_CONNECTION_CLIENT_NAME: ${DATABASE_CONNECTION_CLIENT_NAME:-evolution_api}
      DATABASE_SAVE_DATA_INSTANCE: ${DATABASE_SAVE_DATA_INSTANCE:-true}
      DATABASE_SAVE_DATA_NEW_MESSAGE: ${DATABASE_SAVE_DATA_NEW_MESSAGE:-true}
      DATABASE_SAVE_MESSAGE_UPDATE: ${DATABASE_SAVE_MESSAGE_UPDATE:-true}
      DATABASE_SAVE_DATA_CONTACTS: ${DATABASE_SAVE_DATA_CONTACTS:-true}
      DATABASE_SAVE_DATA_CHATS: ${DATABASE_SAVE_DATA_CHATS:-true}
      
      # RabbitMQ Configuration
      RABBITMQ_ENABLED: ${RABBITMQ_ENABLED:-true}
      RABBITMQ_URI: ${RABBITMQ_URI:-amqp://root:BAmH4TiAPwBQAy8y2tx41BJXcrBa7y2t@rabbitmq:5672/default}
      RABBITMQ_EXCHANGE_NAME: ${RABBITMQ_EXCHANGE_NAME:-evolution_api}
      RABBITMQ_GLOBAL_ENABLED: ${RABBITMQ_GLOBAL_ENABLED:-false}
      RABBITMQ_EVENTS_APPLICATION_STARTUP: ${RABBITMQ_EVENTS_APPLICATION_STARTUP:-true}
      RABBITMQ_EVENTS_INSTANCE_CREATE: ${RABBITMQ_EVENTS_INSTANCE_CREATE:-true}
      RABBITMQ_EVENTS_INSTANCE_DELETE: ${RABBITMQ_EVENTS_INSTANCE_DELETE:-true}
      RABBITMQ_EVENTS_QRCODE_UPDATED: ${RABBITMQ_EVENTS_QRCODE_UPDATED:-true}
      RABBITMQ_EVENTS_MESSAGES_SET: ${RABBITMQ_EVENTS_MESSAGES_SET:-true}
      RABBITMQ_EVENTS_MESSAGES_UPSERT: ${RABBITMQ_EVENTS_MESSAGES_UPSERT:-true}
      RABBITMQ_EVENTS_MESSAGES_EDITED: ${RABBITMQ_EVENTS_MESSAGES_EDITED:-true}
      RABBITMQ_EVENTS_MESSAGES_UPDATE: ${RABBITMQ_EVENTS_MESSAGES_UPDATE:-true}
      RABBITMQ_EVENTS_MESSAGES_DELETE: ${RABBITMQ_EVENTS_MESSAGES_DELETE:-true}
      RABBITMQ_EVENTS_SEND_MESSAGE: ${RABBITMQ_EVENTS_SEND_MESSAGE:-true}
      RABBITMQ_EVENTS_CONTACTS_SET: ${RABBITMQ_EVENTS_CONTACTS_SET:-true}
      RABBITMQ_EVENTS_CONTACTS_UPSERT: ${RABBITMQ_EVENTS_CONTACTS_UPSERT:-true}
      RABBITMQ_EVENTS_CONTACTS_UPDATE: ${RABBITMQ_EVENTS_CONTACTS_UPDATE:-true}
      RABBITMQ_EVENTS_PRESENCE_UPDATE: ${RABBITMQ_EVENTS_PRESENCE_UPDATE:-true}
      RABBITMQ_EVENTS_CHATS_SET: ${RABBITMQ_EVENTS_CHATS_SET:-true}
      RABBITMQ_EVENTS_CHATS_UPSERT: ${RABBITMQ_EVENTS_CHATS_UPSERT:-true}
      RABBITMQ_EVENTS_CHATS_UPDATE: ${RABBITMQ_EVENTS_CHATS_UPDATE:-true}
      RABBITMQ_EVENTS_CHATS_DELETE: ${RABBITMQ_EVENTS_CHATS_DELETE:-true}
      RABBITMQ_EVENTS_GROUPS_UPSERT: ${RABBITMQ_EVENTS_GROUPS_UPSERT:-true}
      RABBITMQ_EVENTS_GROUP_UPDATE: ${RABBITMQ_EVENTS_GROUP_UPDATE:-true}
      RABBITMQ_EVENTS_GROUP_PARTICIPANTS_UPDATE: ${RABBITMQ_EVENTS_GROUP_PARTICIPANTS_UPDATE:-true}
      RABBITMQ_EVENTS_CONNECTION_UPDATE: ${RABBITMQ_EVENTS_CONNECTION_UPDATE:-true}
      RABBITMQ_EVENTS_CALL: ${RABBITMQ_EVENTS_CALL:-true}
      RABBITMQ_EVENTS_TYPEBOT_START: ${RABBITMQ_EVENTS_TYPEBOT_START:-true}
      RABBITMQ_EVENTS_TYPEBOT_CHANGE_STATUS: ${RABBITMQ_EVENTS_TYPEBOT_CHANGE_STATUS:-true}
      
      # AWS SQS Configuration
      SQS_ENABLED: ${SQS_ENABLED:-false}
      SQS_ACCESS_KEY_ID: ${SQS_ACCESS_KEY_ID:-}
      SQS_SECRET_ACCESS_KEY: ${SQS_SECRET_ACCESS_KEY:-}
      SQS_ACCOUNT_ID: ${SQS_ACCOUNT_ID:-}
      SQS_REGION: ${SQS_REGION:-}
      
      # WebSocket Configuration
      WEBSOCKET_ENABLED: ${WEBSOCKET_ENABLED:-false}
      WEBSOCKET_GLOBAL_EVENTS: ${WEBSOCKET_GLOBAL_EVENTS:-false}
      
      # WhatsApp Business Configuration
      WA_BUSINESS_TOKEN_WEBHOOK: ${WA_BUSINESS_TOKEN_WEBHOOK:-evolution}
      WA_BUSINESS_URL: ${WA_BUSINESS_URL:-https://graph.facebook.com}
      WA_BUSINESS_VERSION: ${WA_BUSINESS_VERSION:-v20.0}
      WA_BUSINESS_LANGUAGE: ${WA_BUSINESS_LANGUAGE:-en_US}
      
      # Webhook Configuration
      WEBHOOK_GLOBAL_ENABLED: ${WEBHOOK_GLOBAL_ENABLED:-false}
      WEBHOOK_GLOBAL_URL: ${WEBHOOK_GLOBAL_URL:-https://URL}
      WEBHOOK_GLOBAL_WEBHOOK_BY_EVENTS: ${WEBHOOK_GLOBAL_WEBHOOK_BY_EVENTS:-false}
      WEBHOOK_EVENTS_APPLICATION_STARTUP: ${WEBHOOK_EVENTS_APPLICATION_STARTUP:-false}
      WEBHOOK_EVENTS_QRCODE_UPDATED: ${WEBHOOK_EVENTS_QRCODE_UPDATED:-true}
      WEBHOOK_EVENTS_MESSAGES_SET: ${WEBHOOK_EVENTS_MESSAGES_SET:-true}
      WEBHOOK_EVENTS_MESSAGES_UPSERT: ${WEBHOOK_EVENTS_MESSAGES_UPSERT:-true}
      WEBHOOK_EVENTS_MESSAGES_EDITED: ${WEBHOOK_EVENTS_MESSAGES_EDITED:-true}
      WEBHOOK_EVENTS_MESSAGES_UPDATE: ${WEBHOOK_EVENTS_MESSAGES_UPDATE:-true}
      WEBHOOK_EVENTS_MESSAGES_DELETE: ${WEBHOOK_EVENTS_MESSAGES_DELETE:-true}
      WEBHOOK_EVENTS_SEND_MESSAGE: ${WEBHOOK_EVENTS_SEND_MESSAGE:-true}
      WEBHOOK_EVENTS_CONTACTS_SET: ${WEBHOOK_EVENTS_CONTACTS_SET:-true}
      WEBHOOK_EVENTS_CONTACTS_UPSERT: ${WEBHOOK_EVENTS_CONTACTS_UPSERT:-true}
      WEBHOOK_EVENTS_CONTACTS_UPDATE: ${WEBHOOK_EVENTS_CONTACTS_UPDATE:-true}
      WEBHOOK_EVENTS_PRESENCE_UPDATE: ${WEBHOOK_EVENTS_PRESENCE_UPDATE:-true}
      WEBHOOK_EVENTS_CHATS_SET: ${WEBHOOK_EVENTS_CHATS_SET:-true}
      WEBHOOK_EVENTS_CHATS_UPSERT: ${WEBHOOK_EVENTS_CHATS_UPSERT:-true}
      WEBHOOK_EVENTS_CHATS_UPDATE: ${WEBHOOK_EVENTS_CHATS_UPDATE:-true}
      WEBHOOK_EVENTS_CHATS_DELETE: ${WEBHOOK_EVENTS_CHATS_DELETE:-true}
      WEBHOOK_EVENTS_GROUPS_UPSERT: ${WEBHOOK_EVENTS_GROUPS_UPSERT:-true}
      WEBHOOK_EVENTS_GROUPS_UPDATE: ${WEBHOOK_EVENTS_GROUPS_UPDATE:-true}
      WEBHOOK_EVENTS_GROUP_PARTICIPANTS_UPDATE: ${WEBHOOK_EVENTS_GROUP_PARTICIPANTS_UPDATE:-true}
      WEBHOOK_EVENTS_CONNECTION_UPDATE: ${WEBHOOK_EVENTS_CONNECTION_UPDATE:-true}
      WEBHOOK_EVENTS_LABELS_EDIT: ${WEBHOOK_EVENTS_LABELS_EDIT:-true}
      WEBHOOK_EVENTS_LABELS_ASSOCIATION: ${WEBHOOK_EVENTS_LABELS_ASSOCIATION:-true}
      WEBHOOK_EVENTS_CALL: ${WEBHOOK_EVENTS_CALL:-true}
      WEBHOOK_EVENTS_TYPEBOT_START: ${WEBHOOK_EVENTS_TYPEBOT_START:-false}
      WEBHOOK_EVENTS_TYPEBOT_CHANGE_STATUS: ${WEBHOOK_EVENTS_TYPEBOT_CHANGE_STATUS:-false}
      WEBHOOK_EVENTS_ERRORS: ${WEBHOOK_EVENTS_ERRORS:-false}
      WEBHOOK_EVENTS_ERRORS_WEBHOOK: ${WEBHOOK_EVENTS_ERRORS_WEBHOOK:-https://url}
      
      # Integrations
      OPENAI_ENABLED: ${OPENAI_ENABLED:-true}
      DIFY_ENABLED: ${DIFY_ENABLED:-true}
      TYPEBOT_ENABLED: ${TYPEBOT_ENABLED:-true}
      TYPEBOT_SEND_MEDIA_BASE64: ${TYPEBOT_SEND_MEDIA_BASE64:-true}
      TYPEBOT_API_VERSION: ${TYPEBOT_API_VERSION:-latest}
      CHATWOOT_ENABLED: ${CHATWOOT_ENABLED:-true}
      CHATWOOT_MESSAGE_READ: ${CHATWOOT_MESSAGE_READ:-true}
      CHATWOOT_MESSAGE_DELETE: ${CHATWOOT_MESSAGE_DELETE:-false}
      CHATWOOT_IMPORT_DATABASE_CONNECTION_URI: ${CHATWOOT_IMPORT_DATABASE_CONNECTION_URI:-postgresql://postgres:BAmH4TiAPwBQAy8y2tx41BJXcrBa7y2t@postgres:5432/chatwoot?sslmode=disable}
      CHATWOOT_IMPORT_PLACEHOLDER_MEDIA_MESSAGE: ${CHATWOOT_IMPORT_PLACEHOLDER_MEDIA_MESSAGE:-true}
      
      # Language
      LANGUAGE: ${LANGUAGE:-es}
      
      # S3 Storage Configuration
      S3_ENABLED: ${S3_ENABLED:-true}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY:-acces_key}
      S3_SECRET_KEY: ${S3_SECRET_KEY:-secret_key}
      S3_BUCKET: ${S3_BUCKET:-typebot}
      S3_PORT: ${S3_PORT:-443}
      S3_ENDPOINT: ${S3_ENDPOINT:-ssminiodevss.daverod.tech}
      S3_USE_SSL: ${S3_USE_SSL:-true}

    ports:
      - "8184:8080" # Mantenemos el puerto para acceder directamente a evoapi si es necesario (no gestionado por Traefik directamente)
    volumes:
      - evolution_v2_instances:/evolution/instances
      - evolution_store:/evolution/store
    networks:
      - dokploy-network
    deploy:  # Sección para configuraciones de despliegue, incluyendo límites de recursos
      resources:
        limits:  # Límites máximos que el contenedor puede usar
          cpus: '1'      # Límite de CPU: 1 core (puedes usar decimales como '0.5' para medio core)
          memory: 2024M   # Límite de memoria: 1024 MB (puedes usar G para GB, K para KB, etc.)
        # reservations: # (Opcional) Reservas mínimas garantizadas (no obligatorio para límites)
        #   cpus: '0.5'
        #   memory: 256M

volumes:
  evolution_v2_instances:
  evolution_store:

networks:
  dokploy-network:
    external: true
    