http:
  routers:
    dokploy-router-app:
      rule: Host(`daverod.tech`)
      service: dokploy-service-app
      entryPoints:
        - web
        - websecure
      middlewares:
        - redirect-to-https
    dokploy-router-app-secure:
      rule: Host(`daverod.tech`)
      service: dokploy-service-app
      entryPoints:
        - websecure
      middlewares: []
      tls:
        certResolver: letsencrypt
  services:
    dokploy-service-app:
      loadBalancer:
        servers:
          - url: http://dokploy:3000
        passHostHeader: true
