services:
  minio_dev:
    image: minio/minio:latest
    hostname: minio_dev
    container_name: minio_dev
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - "../files/s3_data:/data"
    networks:
      - dokploy-network 
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minio}
      MINIO_ROOT_PASSWORD: ${ADMIN_PASSWORD:-minio123}
    command: server /data --console-address ":9001"
    deploy:  # Sección para configuraciones de despliegue, incluyendo límites de recursos
      resources:
        limits:  # Límites máximos que el contenedor puede usar
          cpus: '1'      # Límite de CPU: 1 core (puedes usar decimales como '0.5' para medio core)
          memory: 2048M   # Límite de memoria: 1024 MB (puedes usar G para GB, K para KB, etc.)
        # reservations: # (Opcional) Reservas mínimas garantizadas (no obligatorio para límites)
        #   cpus: '0.5'
        #   memory: 256M


# This service just makes sure a bucket with the right policies is created
  createbuckets_dev:
    image: minio/mc:latest
    hostname: nbuckdev
    container_name: nbuckdev
    depends_on:
      - minio_dev
    entrypoint: |
        /bin/sh -c "
        sleep 10;
        /usr/bin/mc config host add minio_dev https://ssapiminiodevss.daverod.tech ${MINIO_ROOT_USER} ${ADMIN_PASSWORD};
        /usr/bin/mc mb minio/respaldos;
        /usr/bin/mc anonymous set public minio/respaldos/public;
        exit 0;
        "

volumes:
  minio-data-test:




networks:
  dokploy-network:
    external: true