services:
  postgres-n8n-dev:
    image: postgres:16-alpine
    restart: always
    hostname: postgres-n8n-dev
    container_name: postgres-n8n-dev
    env_file: .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '8432:5432'
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 10s
      timeout: 5s
      retries: 5
    command: |
      postgres -c max_connections=1000 -c listen_addresses=0.0.0.0
    volumes:
      - postgres_data_n8n:/var/lib/postgresql/data
    networks:
      - dokploy-network
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    restart: always
    hostname: n8n-editor-dev
    container_name: n8n-editor-dev
    environment:
      - N8N_HOST=${N8N_HOST}
      - N8N_PORT=${N8N_PORT}
      - N8N_EDITOR_BASE_URL=https://${N8N_HOST}/
      - WEBHOOK_URL=https://${WEBHOOK_URL}/
      - VUE_APP_URL_BASE_API=${VUE_APP_URL_BASE_API}
      - N8N_PROTOCOL=${N8N_PROTOCOL}
      - NODE_ENV=production
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - DB_TYPE=${DB_TYPE}
      - DB_POSTGRESDB_HOST=${DB_POSTGRESDB_HOST}
      - DB_POSTGRESDB_PORT=${DB_POSTGRESDB_PORT}
      - DB_POSTGRESDB_DATABASE=${DB_POSTGRESDB_DATABASE}
      - DB_POSTGRESDB_USER=${DB_POSTGRESDB_USER}
      - DB_POSTGRESDB_PASSWORD=${DB_POSTGRESDB_PASSWORD}
      - N8N_SECURE_COOKIE=${N8N_SECURE_COOKIE}
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=${N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS}
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - N8N_LICENSE_ACTIVATION_KEY=${N8N_LICENSE_ACTIVATION_KEY}
      - N8N_LICENSE_SERVER_URL=${N8N_LICENSE_SERVER_URL}
      - N8N_COMMUNITY_PACKAGES_ENABLED=true
      - EXECUTIONS_MODE=queue
      - QUEUE_BULL_REDIS_HOST=redis
      - QUEUE_BULL_REDIS_PORT=6379
      - QUEUE_BULL_REDIS_DB=2
      - NODE_FUNCTION_ALLOW_EXTERNAL=moment,lodash,moment-with-locales
      - EXECUTIONS_DATA_PRUNE=true
      - EXECUTIONS_DATA_MAX_AGE=336
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      postgres-n8n-dev:
        condition: service_healthy
    ports:
      - '5678:5678'
    networks:
      - dokploy-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.developn8n-n8n-dev-vwkedd-15-web.rule=Host(`n8ndavetech.daverod.tech`)
      - traefik.http.routers.developn8n-n8n-dev-vwkedd-15-web.entrypoints=web
      - traefik.http.services.developn8n-n8n-dev-vwkedd-15-web.loadbalancer.server.port=5678
      - traefik.http.routers.developn8n-n8n-dev-vwkedd-15-web.service=developn8n-n8n-dev-vwkedd-15-web
      - traefik.http.routers.developn8n-n8n-dev-vwkedd-15-web.middlewares=redirect-to-https@file
      - traefik.http.routers.developn8n-n8n-dev-vwkedd-15-websecure.rule=Host(`n8ndavetech.daverod.tech`)
      - traefik.http.routers.developn8n-n8n-dev-vwkedd-15-websecure.entrypoints=websecure
      - traefik.http.services.developn8n-n8n-dev-vwkedd-15-websecure.loadbalancer.server.port=5678
      - traefik.http.routers.developn8n-n8n-dev-vwkedd-15-websecure.service=developn8n-n8n-dev-vwkedd-15-websecure
      - traefik.http.routers.developn8n-n8n-dev-vwkedd-15-websecure.tls.certresolver=letsencrypt
  n8n_webhook:
    image: docker.n8n.io/n8nio/n8n:latest
    restart: always
    command: webhook
    container_name: webhookn8ndev
    env_file: .env
    environment:
      - DB_TYPE=${DB_TYPE}
      - DB_POSTGRESDB_HOST=${DB_POSTGRESDB_HOST}
      - DB_POSTGRESDB_PORT=${DB_POSTGRESDB_PORT}
      - DB_POSTGRESDB_DATABASE=${DB_POSTGRESDB_DATABASE}
      - DB_POSTGRESDB_USER=${DB_POSTGRESDB_USER}
      - DB_POSTGRESDB_PASSWORD=${DB_POSTGRESDB_PASSWORD}
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - N8N_HOST=${N8N_HOST}
      - N8N_EDITOR_BASE_URL=https://${N8N_HOST}/
      - N8N_PORT=${N8N_PORT}
      - WEBHOOK_URL=https://${WEBHOOK_URL}/
      - VUE_APP_URL_BASE_API=${VUE_APP_URL_BASE_API}
      - N8N_PROTOCOL=${N8N_PROTOCOL}
      - NODE_ENV=production
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - N8N_SECURE_COOKIE=${N8N_SECURE_COOKIE}
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=${N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS}
      - N8N_LICENSE_ACTIVATION_KEY=${N8N_LICENSE_ACTIVATION_KEY}
      - N8N_LICENSE_SERVER_URL=${N8N_LICENSE_SERVER_URL}
      - N8N_COMMUNITY_PACKAGES_ENABLED=true
      - EXECUTIONS_MODE=queue
      - QUEUE_BULL_REDIS_HOST=redis
      - QUEUE_BULL_REDIS_PORT=6379
      - QUEUE_BULL_REDIS_DB=2
      - NODE_FUNCTION_ALLOW_EXTERNAL=moment,lodash,moment-with-locales
      - EXECUTIONS_DATA_PRUNE=True
      - EXECUTIONS_DATA_MAX_AGE=336
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - dokploy-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.developn8n-n8n-dev-vwkedd-16-web.rule=Host(`webhookn8ndevelop.daverod.tech`)
      - traefik.http.routers.developn8n-n8n-dev-vwkedd-16-web.entrypoints=web
      - traefik.http.services.developn8n-n8n-dev-vwkedd-16-web.loadbalancer.server.port=5678
      - traefik.http.routers.developn8n-n8n-dev-vwkedd-16-web.service=developn8n-n8n-dev-vwkedd-16-web
      - traefik.http.routers.developn8n-n8n-dev-vwkedd-16-web.middlewares=redirect-to-https@file
      - traefik.http.routers.developn8n-n8n-dev-vwkedd-16-websecure.rule=Host(`webhookn8ndevelop.daverod.tech`)
      - traefik.http.routers.developn8n-n8n-dev-vwkedd-16-websecure.entrypoints=websecure
      - traefik.http.services.developn8n-n8n-dev-vwkedd-16-websecure.loadbalancer.server.port=5678
      - traefik.http.routers.developn8n-n8n-dev-vwkedd-16-websecure.service=developn8n-n8n-dev-vwkedd-16-websecure
      - traefik.http.routers.developn8n-n8n-dev-vwkedd-16-websecure.tls.certresolver=letsencrypt
  n8n_worker:
    image: docker.n8n.io/n8nio/n8n:latest
    command: worker --concurrency=5
    container_name: n8nworker
    environment:
      - DB_TYPE=${DB_TYPE}
      - DB_POSTGRESDB_HOST=${DB_POSTGRESDB_HOST}
      - DB_POSTGRESDB_PORT=${DB_POSTGRESDB_PORT}
      - DB_POSTGRESDB_DATABASE=${DB_POSTGRESDB_DATABASE}
      - DB_POSTGRESDB_USER=${DB_POSTGRESDB_USER}
      - DB_POSTGRESDB_PASSWORD=${DB_POSTGRESDB_PASSWORD}
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=${N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS}
      - N8N_HOST=${N8N_HOST}
      - N8N_EDITOR_BASE_URL=https://${N8N_HOST}/
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - WEBHOOK_URL=https://${WEBHOOK_URL}/
      - EXECUTIONS_MODE=queue
      - QUEUE_BULL_REDIS_HOST=redis
      - QUEUE_BULL_REDIS_PORT=6379
      - QUEUE_BULL_REDIS_DB=2
      - NODE_FUNCTION_ALLOW_EXTERNAL=moment,lodash,moment-with-locales
      - EXECUTIONS_DATA_PRUNE=True
      - EXECUTIONS_DATA_MAX_AGE=336
    networks:
      - dokploy-network
networks:
  dokploy-network:
    external: true
volumes:
  n8n_data: null
  postgres_data_n8n: null
